name: SuperbVote
main: io.minimum.minecraft.superbvote.SuperbVote
author: tuxed
version: ${project.version}
depend: [Votifier]
softdepend: [PlaceholderAPI, Vault]
commands:
  superbvote:
    description: SuperbVote main command.
    aliases: [sv]
  vote:
    description: SuperbVote vote command.
permissions:
  superbvote.notify:
    default: true